language: python
matrix:
  include:
      - python: 3.7
        dist: xenial
        sudo: true
      - python: 3.6
      - python: 3.5
      - python: 3.4
      - python: 2.7
notifications:
  email: false
install: pip install tox-travis coverage==4.3.4 codeclimate-test-reporter
script: tox
after_success:
- test $TRAVIS_PYTHON_VERSION = "3.6" && CODECLIMATE_REPO_TOKEN=5105b82f0baefc540e934fe31b30a3e05d884991340e9856a83a8f2460aa2ef3
  codeclimate-test-reporter --file .coverage.py36
deploy:
  on:
    repo: catmaid/catpy
    python: 3.6
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: FoRzNQ9+a0/gjbmJ71G2sN9jRtbaxxhv3TPJtJwTFAmRE7mRDj1xuksP2sSbmoCc1m1zZtwdeMvwdhM7t/O6OLvx4QmGZwC+QPHdWuyuAbfsdUNQ/4/wPysRJjRsRPeO8gNJTsg05Ro/AxTBZABACiYexbo6bLyKRrVLUq4Ie7OxWbEmLzEjPwlQVjaiMIxVqjGoD9t4OmZLdK9URKrjnJ8XSTLkxRd5E7+T7pTWoSTL0lEpwhs11n3CUAkIFukQN3GrYpcT//TsZfBAk+zQxzyCLcYx+nJjFbOb3vOzySVBB0hHuQEQvQJxj7ufjAVjge4COUXX5aRKNmVz++qEs16FTBs6e+y9kcZyJeg7eErmdnmtumr0DHDxIZQtZ2jwu9CCioTLt7LkWyIbCJ3V8+Mbken/psmoegYX3R+0D3/nVEwfAvKm2GgmL6mUSO1sBwYPM6akcb5eLHPwWQQhn9Drh8OifzD9pbDVcq9tge1IiPGMM9118j2Wy5rC7FVFHKIF7BUNJ7IwHlfjTfhrdt/wtlJ+qSi6QIKJygwHHNscn75NzU3Psp1lrvDxdiC3cq4ThbBxjv8EMOKBWWxV5kWcV9YLWxm7LzfOSVIAw1v1We4DjGM+FdVetGQnPOXMepwkh+UsiPLMgD4LZWvtQXkGaLN/6b02QiIhQWHOaxo=
  provider: pypi
  user: clbarnes
