language: python
python: 3.5
notifications:
  email: false
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py27
install: pip install -U tox
script: tox -e ${TOXENV}
after_success:
    - CODECLIMATE_REPO_TOKEN=5105b82f0baefc540e934fe31b30a3e05d884991340e9856a83a8f2460aa2ef3 codeclimate-test-reporter
deploy:
  on:
    condition: $TOXENV == py27
    repo: catmaid/catpy
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: D0Z6YFFY6cOPwYeEXh7XHt9K4/cVYk/oWxDa5oMHfTFvNl0T/qIxAECMuNp7sEIvRGT/sOwDBnH3UuBOU50QnJkeALTcbwkeVdsVmRaK9q7siUIJTkCi8ov1HNe6NS47Px4bCuz64WkvYw7lvwPMdrzP0yr7DwSkk+bo1f6SGxpANWihU1lJB7DixCJB+yy+EB+hfM19a/p9SHSYM793qsKFZ1dq8u72yWNvmhkPAKb7HOEtCM9pbzeQdDklOkbR+AUxj2EvtbbQYCow2Ymgvd5RRR1KZajuOTTBwgnJIiirBtO6j6B5dmBqgRdSNNWRCx16RzLny6b64P0xg9E8gSFtYLg7M+BBbnkJ11WrzyPD4KVaBZAaPokrY/fP0xFgQ4++brZdziy27eA8B9a71+3sS7Ilq3CaLBiaIc+Vcn/h3gqOPTCn2dcazN3ZwAKr+YGqpfsuAx/dtTmelLEovGt7bvjl/G5LxTUfgkA9JL2JyZmgOIJbEePxW7xoyASh2t7u6z4+s+hrlIJC50iPtNh+Q9Bk/JfcSKCSKkZDdCszlK4MV/WSEC82qutLXHkCHPWoWeHRp9I2X8pG2+mzuvQdBtGfbEdqA5JSLw63g5dyrzmK42TEzmAtOGzxBPfBjWXkNEZLkcb2qmJcZmtiY1YPBXsWf88IvZ4cV1Avz9E=
  provider: pypi
  user: aschampion
